Fix typo in JUnit template after Change I792c5971
java.lang.RuntimeException: Cannot read _template__of_JUnit.xml
Caused by: org.jdom.JDOMException: Unexpected character '"' (code 34) expected space, or '>' or "/>"
 at [row,col {unknown-source}]: [11,2335]
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:236)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:312)
	at com.intellij.configurationStore.schemeManager.SchemeDataHolderImpl.read(SchemeDataHolderImpl.kt:21)
	... 44 more

Bug: N/A
Test: N/A
Change-Id: I0455b2883dfa90ec13144eea18e7436477070247