ml-api: Fix data dependencies needed to run tests
I4130093d3bb25f introduced a copy of IdeaTestSuiteBase that is aiplugin
specific, but some data dependencies were not included. As a result,
running tests via bazel was broken:

```
bazel test //tools/vendor/google/ml/aiplugin/core:aiplugin.core-tests_test
```

will result in:

```
ERROR: Error initializing test suite, tests will likely fail following this error
java.lang.IllegalArgumentException: File "tools/adt/idea/adt-testutils/test-log.properties" not found at "/private/var/tmp/_bazel_gharrma/601100d594cb32ffc8fae4d9d2f7ad50/sandbox/darwin-sandbox/7200/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/tools/vendor/google/ml/aiplugin/core/aiplugin.core-tests_tests.runfiles/__main__"
        at com.android.testutils.TestUtils.resolveWorkspacePath(TestUtils.java:234)
...
java.lang.AssertionError: JNA library is not available
  at com.intellij.ui.mac.foundation.Foundation.<clinit>(Foundation.java:30)
  at com.intellij.ui.mac.foundation.Foundation$NSAutoreleasePool.<init>(Foundation.java:491)
  at com.intellij.ui.components.MacScrollBarUI.callMac(MacScrollBarUI.java:181)
```

This CL includes the same data dependencies as present in
tools/adt/idea/adt-testutils/BUILD.

Bug: N/A
Test: running bazel command above on a Mac succeeds
Change-Id: I7c19e1275c68e94a343d1a38e7fbb98baa52903b