MockEvaluationContextUtils: adapt to IntelliJ 2026.2
This avoids a test failure with IntelliJ 2026.2 caused by:

  NullPointerException: Cannot invoke
  "kotlinx.coroutines.CoroutineScope.getCoroutineContext()" because
  "$this$newCoroutineContext" is null"

Bug: not filed
Test: ComposeStateObjectRendererTest.renderInteger
Change-Id: If990c4b645e08a8780b931589c49724361d4c630