Update Jewel to 0.24.2 in adt-ui-compose.
The version was last updated to 0.24.1 in ag/29303574, although the commit message says 0.24.2.

The version 0.24.1 is causing the compilation error below:

e: StudioComposePanel.kt:19:35 Unresolved reference: JewelComposeNoThemePanel
e: StudioComposePanel.kt:24:5 Functions which invoke @Composable functions must be marked with the @Composable annotation
e: StudioComposePanel.kt:27:3 Unresolved reference: JewelComposeNoThemePanel
e: StudioComposePanel.kt:27:30 @Composable invocations can only happen from the context of a @Composable function

Bug: 365087143
Test: manual tests
Change-Id: Ifa7b4c24138801332545ee302e6127cca03bbd15