Android: Add missing id for RulesPersistentStateConverterProvider definition.
id is added to resolve following exception:
SEVERE - #c.i.o.p.i.ProjectManagerImpl - supplier.get()!!.deprecatedId must not be null
java.lang.NullPointerException: supplier.get()!!.deprecatedId must not be null

(cherry picked from commit 83e49396e6ebd5a063b3ec673635194a109e6e42)

Change-Id: If5c67cc8f2d9bff072a82cc4e484e76bd273744b