Fix LintIdeGradleDetectorTest
...which started failing due to more asynchronous kts handling:

ERROR: PSI/document/model changes are not allowed during highlighting, because it leads to the daemon unnecessary restarts. If you really do need to start write action during the highlighting, you can pass `canChangeDocument=true` to the CodeInsightTestFixtureImpl#instantiateAndRun() and accept the daemon unresponsiveness/blinking/slowdowns.

java.lang.AssertionError: PSI/document/model changes are not allowed during highlighting, because it leads to the daemon unnecessary restarts. If you really do need to start write action during the highlighting, you can pass `canChangeDocument=true` to the CodeInsightTestFixtureImpl#instantiateAndRun() and accept the daemon unresponsiveness/blinking/slowdowns.
	at com.intellij.codeInsight.daemon.impl.FileStatusMap.assertAllowModifications(FileStatusMap.java:144)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap.markAllFilesDirty(FileStatusMap.java:123)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.restart(DaemonCodeAnalyzerImpl.java:630)

Note that the proper way to wait for scripting to initialize can be
found in AbstractK2LocalInspectionTest:

private fun processKotlinScriptIfNeeded(file: PsiFile) {
    if (file !is KtFile || !file.isScript()) return

    runWithModalProgressBlocking(project, "AbstractK2LocalInspectionTest") {
        KotlinScriptService.getInstance(project).load(file.alwaysVirtualFile)
    }
}
... which is called after myFixture.configureByFiles and before
doTest(). But in our case the Kotlin scripts do not belong to a
source root (and we disable their highlighting because of that), so
the call is a noop.

Bug: N/A
Test: it
Change-Id: Idfbe0ba355675a626f4b319ab934acba9ebf9e79