Revert "Disable RenderingBuildStatusManagerTest.testProjectStatusManagerStates"
This reverts commit 3d063b35e65a901aa04572503297fc2d80a1c956.

Reason for revert: build failure: tools/adt/idea/compose-designer/testSrc/com/android/tools/idea/compose/gradle/preview/RenderingBuildStatusManagerTest.kt:74:3: error: this annotation is not repeatable
  @Ignore("b/356192917")
  ^

Change-Id: I9d9f7fd2a7e5d47c3d092fd90f1c45bb93a0c2d7