Depend on ....android.projectSystem.gradle.models
Otherwise I get a

/home/juancnuno/Development/studio-main/tools/adt/idea/android/navigator
  /testSrc/com/android/tools/idea/navigator
  /AndroidProjectViewTest.java:66:69
java: cannot access com.android.tools.idea.gradle.model
.IdeAndroidArtifact
  class file for com.android.tools.idea.gradle.model.IdeAndroidArtifact
  not found

compilation error when I build with IDEA

Bug: Not applicable
Test: Not applicable
Change-Id: Ic8883efe7079cc78ba13ef967218583858c46d04